import Link from "next/link";

const phones = ["+94 77 781 0341", "+94 76 139 2811", "+94 76 098 5462", "+94 77 638 0753"];
const wa = "https://wa.me/94776380753";
const website = "https://www.sunrisecabskandy.com/";

export default function ContactPage() {
  return <main className="min-h-screen bg-[#030303] px-5 py-10 text-white md:px-12"><div className="mx-auto max-w-6xl"><Link href="/" className="text-xs uppercase tracking-[.25em] text-[#ffdd8a]">← SunriseCabs</Link><header className="py-20"><p className="eyebrow">Contact / direct routes</p><h1 className="display mt-5 text-6xl md:text-8xl">Talk to <span className="sun italic">Sunrise.</span></h1><p className="mt-7 max-w-2xl text-sm leading-7 text-white/50">These are public contact routes found in current listings. For the fastest booking conversation, WhatsApp is the primary showcase CTA.</p></header><section className="grid gap-5 md:grid-cols-2"><a href={wa} target="_blank" rel="noreferrer" className="glass rounded-[2rem] p-8 transition hover:-translate-y-1"><p className="eyebrow">WhatsApp / public route</p><h2 className="mt-10 text-3xl font-semibold text-[#25D366]">Chat on WhatsApp →</h2><p className="mt-3 text-sm text-white/40">+94 77 638 0753</p></a><a href={website} target="_blank" rel="noreferrer" className="glass rounded-[2rem] p-8 transition hover:-translate-y-1"><p className="eyebrow">Public website</p><h2 className="mt-10 text-3xl font-semibold text-[#ffe09a]">sunrisecabskandy.com →</h2><p className="mt-3 text-sm text-white/40">Official-site reference found in public business listings.</p></a></section><section className="mt-6 glass rounded-[2rem] p-8 md:p-10"><p className="eyebrow">Phone routes</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{phones.map(p=><a key={p} href={`tel:${p.replace(/\s/g,"")}`} className="rounded-2xl border border-white/10 bg-white/[.025] p-5 text-lg text-white/80 hover:border-[#f4b942]/40">{p}</a>)}</div><p className="mt-6 text-xs leading-5 text-white/30">Public listings can change. Confirm the correct number, vehicle, availability, deposit and final price directly with Sunrise.</p></section><section className="mt-6 rounded-[2rem] border border-white/10 p-8 md:p-10"><p className="eyebrow">Social / verification</p><h2 className="display mt-4 text-4xl">WhatsApp is verified. <span className="sun italic">Facebook is not guessed.</span></h2><p className="mt-5 max-w-3xl text-sm leading-7 text-white/45">Public sources reference Sunrise-related Facebook pages, but an exact current official Facebook profile URL was not independently verified in this research pass. The site therefore does not fabricate a Facebook handle. This keeps the showcase accurate.</p></section><footer className="mt-16 border-t border-white/10 py-10 text-xs text-white/35"><Link href="/" className="text-[#ffdd8a]">Return to showcase →</Link></footer></div></main>;
}
