'use client';

import dynamic from 'next/dynamic';
import { useEffect, useMemo, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, CarFront, Menu, MessageCircle, Move3D, Sparkles, Users, X } from 'lucide-react';

const Vehicle3D = dynamic(() => import('../components/vehicle/Vehicle3D'), { ssr: false, loading: () => <div className="vehicle-3d grid place-items-center text-[10px] uppercase tracking-[.35em] text-black/35">Loading digital vehicle</div> });

type Kind = 'hatch' | 'suv' | 'van' | 'sedan';
type Vehicle = { id: string; name: string; kind: Kind; category: string; seats: number; bags: number; economy: string; rate?: number; note: string };
const fleet: Vehicle[] = [
 {id:'wagon',name:'Suzuki Wagon R',kind:'hatch',category:'CITY / SELF DRIVE',seats:4,bags:2,economy:'18–22 km/L',rate:8000,note:'Published rental reference; confirm current Sunrise availability.'},
 {id:'vezel',name:'Honda Vezel',kind:'suv',category:'HYBRID / SUV',seats:5,bags:2,economy:'Hybrid',rate:11000,note:'Sri Lankan rental-market reference; confirm exact Sunrise trim.'},
 {id:'prius',name:'Toyota Prius',kind:'hatch',category:'HYBRID / COMFORT',seats:5,bags:2,economy:'Hybrid',note:'Market showcase vehicle; Sunrise-specific availability requires confirmation.'},
 {id:'aqua',name:'Toyota Aqua',kind:'hatch',category:'HYBRID / CITY',seats:5,bags:2,economy:'Hybrid',note:'Market showcase vehicle; quote required.'},
 {id:'axio',name:'Toyota Axio',kind:'sedan',category:'SEDAN / TOURING',seats:5,bags:3,economy:'Petrol / Hybrid',note:'Sri Lankan-market showcase vehicle; quote required.'},
 {id:'kdh',name:'Toyota KDH',kind:'van',category:'VAN / GROUPS',seats:10,bags:5,economy:'Diesel',note:'Showcase reference; confirm exact KDH generation and Sunrise fleet status.'},
 {id:'glory',name:'DFSK Glory',kind:'suv',category:'7-SEAT / SUV',seats:7,bags:3,economy:'Petrol',note:'Sri Lankan-market showcase reference; Sunrise availability requires confirmation.'},
 {id:'hiace',name:'Toyota HiAce',kind:'van',category:'VAN / GROUPS',seats:12,bags:6,economy:'Diesel',note:'Category showcase; confirm exact configuration and availability.'}
];
const whatsapp='https://wa.me/94761392811';
const money=(n:number)=>`Rs. ${n.toLocaleString('en-LK')}`;

export default function Home(){
 const [menu,setMenu]=useState(false); const [active,setActive]=useState('wagon'); const [days,setDays]=useState(3); const [loading,setLoading]=useState(true); const [cursor,setCursor]=useState({x:-100,y:-100});
 useEffect(()=>{const timer=setTimeout(()=>setLoading(false),1550); const move=(e:MouseEvent)=>setCursor({x:e.clientX,y:e.clientY}); window.addEventListener('mousemove',move,{passive:true}); return()=>{clearTimeout(timer);window.removeEventListener('mousemove',move)}},[]);
 const selected=useMemo(()=>fleet.find(v=>v.id===active)??fleet[0],[active]);
 return <main className="sunrise-site min-h-screen bg-[#f4f4f1] text-black">
  {loading&&<div className="loader"><div className="loader-inner"><div className="loader-kicker">KANDY / SRI LANKA</div><div className="loader-mark">SUNRISE<span>CABS</span></div><div className="loader-line"><span/></div><div className="loader-meta">DIGITAL MOBILITY STUDIO</div></div></div>}
  <div className="car-cursor" style={{left:cursor.x,top:cursor.y}} aria-hidden="true"/>
  <header className="site-header"><a href="#top" className="brand"><span className="brand-symbol">SC</span><span>SUNRISE<br/>CABS</span></a><div className="header-center">KANDY / SRI LANKA / 01—08</div><nav className="desktop-nav" aria-label="Primary"><a href="#fleet">Fleet</a><a href="#experience">Experience</a><a href="#journeys">Journeys</a><a href="#estimate">Estimate</a></nav><a className="header-action" href={whatsapp} target="_blank" rel="noreferrer">ENQUIRE <ArrowUpRight size={14}/></a><button className="mobile-menu" onClick={()=>setMenu(!menu)} aria-label="Open navigation">{menu?<X/>:<Menu/>}</button></header>
  {menu&&<div className="mobile-panel"><a href="#fleet" onClick={()=>setMenu(false)}>Fleet</a><a href="#experience" onClick={()=>setMenu(false)}>Experience</a><a href="#journeys" onClick={()=>setMenu(false)}>Journeys</a><a href="#estimate" onClick={()=>setMenu(false)}>Estimate</a><a href={whatsapp}>WhatsApp</a></div>}

  <section id="top" className="ds-hero"><div className="hero-number">01</div><div className="hero-copy"><p className="micro">SUNRISECABS / AUTOMOTIVE MOBILITY</p><h1>Move<br/><em>beautifully.</em></h1><p className="hero-description">A Kandy-born rental and travel showcase designed around the vehicle itself — clear information, considered motion and a digital garage you can explore.</p><div className="hero-links"><a href="#fleet">Explore the fleet <ArrowDownRight size={16}/></a><a href="#experience">Discover the studio <ArrowDownRight size={16}/></a></div></div><div className="hero-stage"><Vehicle3D kind={selected.kind}/><div className="stage-caption"><span>Selected / {selected.name}</span><span>DRAG TO ROTATE</span></div></div><div className="hero-rail"><span>SCROLL TO EXPLORE</span><div className="rail-line"/><span>06.08.26</span></div></section>

  <section className="manifesto"><div className="section-index">02 / VISION</div><div className="manifesto-title">The vehicle<br/><em>comes first.</em></div><div className="manifesto-copy"><p>Inspired by contemporary automotive design studios, SunriseCabs is presented as an editorial collection rather than a catalogue of generic cards.</p><p>We borrow the principles — oversized type, full-bleed visual moments, precise grids, behind-the-scenes storytelling and deliberate motion — while creating a distinct Sunrise identity.</p></div></section>

  <section id="experience" className="experience"><div className="experience-top"><div><span className="section-index">03 / DIGITAL GARAGE</span><h2>Explore<br/><em>&amp; create.</em></h2></div><p>Choose a vehicle and let the studio change with it. The 3D scene is deliberately lightweight so the experience remains usable on phones and laptops.</p></div><div className="garage-grid"><div className="garage-main"><Vehicle3D kind={selected.kind}/><div className="garage-overlay"><span>3D / {selected.name}</span><span>STUDIO LIGHTING / LIVE</span></div></div><div className="garage-info"><span className="micro">CURRENT SELECTION</span><h3>{selected.name}</h3><p>{selected.note}</p><div className="spec-list"><div><span>PASSENGERS</span><strong>{selected.seats}</strong></div><div><span>LUGGAGE</span><strong>{selected.bags}</strong></div><div><span>TYPE</span><strong>{selected.kind}</strong></div><div><span>EFFICIENCY</span><strong>{selected.economy}</strong></div></div><a href={whatsapp} target="_blank" rel="noreferrer" className="black-button">Ask about this vehicle <MessageCircle size={15}/></a></div></div></section>

  <section id="fleet" className="fleet-section"><div className="fleet-heading"><div><span className="section-index">04 / COLLECTION</span><h2>A collection<br/><em>for every road.</em></h2></div><p>Swipe or scroll through the library. Select any vehicle to stage it in the digital garage.</p></div><div className="fleet-strip">{fleet.map((v,i)=><button key={v.id} className={`fleet-item ${active===v.id?'is-active':''}`} onClick={()=>setActive(v.id)}><div className="fleet-visual"><Vehicle3D kind={v.kind}/><span className="fleet-no">0{i+1}</span><span className="fleet-view">VIEW 3D <Move3D size={12}/></span></div><div className="fleet-meta"><span>{v.category}</span><h3>{v.name}</h3><div><span>{v.seats} seats</span><span>{v.bags} bags</span><span>{v.economy}</span></div></div></button>)}</div></section>

  <section id="journeys" className="journey-section"><div className="journey-intro"><span className="section-index">05 / THE JOURNEY</span><h2>Not just<br/><em>a rental.</em></h2><p>Design the experience around how people actually travel through Sri Lanka.</p></div><div className="journey-list">{['Airport arrival','Kandy → Ella','Hotel transfer','Family touring','Corporate travel','Island-wide journey'].map((item,i)=><a href={whatsapp} target="_blank" rel="noreferrer" key={item} className="journey-row"><span>0{i+1}</span><strong>{item}</strong><span>ENQUIRE <ArrowUpRight size={15}/></span></a>)}</div></section>

  <section id="estimate" className="estimate-section"><div className="estimate-intro"><span className="section-index">06 / TRIP PREVIEW</span><h2>Make it<br/><em>real.</em></h2><p>A transparent showcase calculator. Rates shown are public references where available, not live availability or a booking confirmation.</p></div><div className="estimate-card"><div className="estimate-top"><span>SELECT VEHICLE</span><span>01—08</span></div><div className="estimate-pills">{fleet.map(v=><button key={v.id} className={active===v.id?'selected':''} onClick={()=>setActive(v.id)}>{v.name}</button>)}</div><div className="estimate-fields"><label>Rental period<select value={days} onChange={e=>setDays(Number(e.target.value))}>{[1,2,3,5,7,10,20,30].map(n=><option key={n} value={n}>{n} {n===1?'day':'days'}</option>)}</select></label><div><span>Selected</span><strong>{selected.name}</strong></div></div><div className="estimate-total"><span>SHOWCASE ESTIMATE</span><strong>{selected.rate?money(selected.rate*days):'QUOTE'}</strong><small>{selected.rate?`${days} × ${money(selected.rate)}/day before any package, mileage or extras.`:'Confirm Sunrise-specific pricing on WhatsApp.'}</small></div><a className="white-button" href={whatsapp} target="_blank" rel="noreferrer">Confirm availability <MessageCircle size={15}/></a></div></section>

  <section className="lab-section"><div className="lab-word">SUNRISE</div><div className="lab-copy"><span className="section-index">07 / LAB</span><h2>Built to feel<br/><em>alive.</em></h2><p>Slow camera movement. Editorial transitions. Interactive vehicle staging. A custom cursor on desktop. Reduced effects on touch devices. The interface changes without making the customer work for it.</p><div className="lab-tags"><span><Sparkles size={13}/> MOTION</span><span><CarFront size={13}/> VEHICLES</span><span><Users size={13}/> PEOPLE</span></div></div></section>
  <footer className="site-footer" id="contact"><div className="footer-brand">SUNRISE<br/><em>CABS</em></div><div><span className="section-index">08 / CONTACT</span><p className="footer-title">Ready when<br/><em>you are.</em></p></div><div className="footer-contact"><p>KANDY / SRI LANKA</p><a href={whatsapp} target="_blank" rel="noreferrer">WhatsApp SunriseCabs <ArrowUpRight size={15}/></a><small>Confirm vehicle, availability, rate and terms directly.</small></div></footer>
 </main>;
}
