'use client';

import { useEffect, useRef } from 'react';

export function CinematicIntro() {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { const el = ref.current; if (!el) return; const onMove = (e: MouseEvent) => { const x = (e.clientX / innerWidth - .5) * 10; const y = (e.clientY / innerHeight - .5) * 6; el.style.setProperty('--mx', `${x}deg`); el.style.setProperty('--my', `${y}deg`); }; addEventListener('mousemove', onMove); return () => removeEventListener('mousemove', onMove); }, []);
  return <section ref={ref} className="relative flex min-h-[85vh] items-center justify-center overflow-hidden bg-black text-white"><div className="absolute h-[30rem] w-[30rem] rounded-full bg-amber-300/10 blur-[120px]"/><div className="relative text-center" style={{ transform: 'perspective(1000px) rotateX(var(--my,0deg)) rotateY(var(--mx,0deg))' }}><p className="text-xs uppercase tracking-[.5em] text-amber-300">Kandy · Sri Lanka</p><h1 className="mt-5 text-[clamp(4rem,12vw,10rem)] font-black tracking-[-.08em]">SUNRISE<span className="text-amber-200">CABS</span></h1><p className="mx-auto mt-4 max-w-xl text-white/50">A cinematic way to discover your next Sri Lankan journey.</p><a href="#fleet" className="mt-8 inline-block rounded-full border border-amber-200/40 px-7 py-3 text-sm transition hover:bg-amber-200 hover:text-black">Explore the fleet ↓</a></div></section>;
}

export function VehicleControls() {
  return <div id="fleet" className="grid gap-4 md:grid-cols-3"><article className="group rounded-[2rem] border border-white/10 bg-white/[.035] p-7 text-white transition duration-500 hover:-translate-y-2 hover:border-amber-200/40"><p className="text-xs uppercase tracking-[.3em] text-amber-300">City favourite</p><h3 className="mt-3 text-3xl font-semibold">Wagon R</h3><p className="mt-2 text-white/50">Compact, practical and presented with a cinematic interactive treatment.</p><div className="mt-8 h-32 rounded-2xl bg-gradient-to-br from-white/10 to-transparent"/><div className="mt-5 flex gap-2"><button className="rounded-full border border-white/10 px-4 py-2 text-xs">Headlights</button><button className="rounded-full border border-white/10 px-4 py-2 text-xs">360° View</button></div></article><article className="group rounded-[2rem] border border-white/10 bg-white/[.035] p-7 text-white transition duration-500 hover:-translate-y-2 hover:border-amber-200/40"><p className="text-xs uppercase tracking-[.3em] text-amber-300">Premium crossover</p><h3 className="mt-3 text-3xl font-semibold">Honda Vezel</h3><p className="mt-2 text-white/50">A polished showcase for longer journeys and premium travel.</p><div className="mt-8 h-32 rounded-2xl bg-gradient-to-br from-white/10 to-transparent"/><div className="mt-5 flex gap-2"><button className="rounded-full border border-white/10 px-4 py-2 text-xs">Headlights</button><button className="rounded-full border border-white/10 px-4 py-2 text-xs">360° View</button></div></article><article className="group rounded-[2rem] border border-white/10 bg-white/[.035] p-7 text-white transition duration-500 hover:-translate-y-2 hover:border-amber-200/40"><p className="text-xs uppercase tracking-[.3em] text-amber-300">Group travel</p><h3 className="mt-3 text-3xl font-semibold">KDH / Glory</h3><p className="mt-2 text-white/50">Showcase category for larger groups. Confirm exact model and availability with SunriseCabs.</p><div className="mt-8 h-32 rounded-2xl bg-gradient-to-br from-white/10 to-transparent"/><div className="mt-5 flex gap-2"><button className="rounded-full border border-white/10 px-4 py-2 text-xs">Explore</button><button className="rounded-full border border-white/10 px-4 py-2 text-xs">Request quote</button></div></article></div>;
}
